//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudOperations.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class student
    {
        [Required]
        public int idstudent { get; set; }
        public string Name { get; set; }
        public string Std { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public string Percentage { get; set; }
    }
}
